---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-ingester-volume-claim
  labels:
    app.kubernetes.io/name: grafana-loki-ingester
    app.kubernetes.io/part-of: grafana-loki
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
