# NOTE:
version: '3.8'
services:
  grafana:
    # default admin user credentials are admin/admin.
    image: grafana/grafana-oss:9.4.7-ubuntu
    container_name: grafana
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
    ports:
      - "6831:6831/udp"
      - "3000:3000"
    restart: on-failure
    volumes:
      - ./docker-data/grafana-data:/var/lib/grafana
    depends_on:
      - loki

  loki:
    image: grafana/loki:2.8.0-arm64
    volumes:
      - ./loki:/home/loki
    ports:
      - "3100:3100"
      - "7946:7946"
    command: "-config.file=/home/loki/loki.yaml"
    depends_on:
      - minio

  minio:
    image: minio/minio:RELEASE.2023-05-18T00-05-36Z
    command: server /data --address ':9000' --console-address ':9001'
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ACCESS_KEY="minio-access-key"
      - MINIO_SECRET_KEY="minio-secret-key"
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ./docker-data/minio-data:/data

  createbuckets:
    image: minio/mc:RELEASE.2023-05-18T16-59-00Z
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc rm -r --force myminio/loki;
      /usr/bin/mc mb myminio/loki;
      /usr/bin/mc policy set public myminio/loki;
      exit 0;
      "
