---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-index-gateway-volume-claim
  labels:
    app.kubernetes.io/name: grafana-loki-index-gateway
    app.kubernetes.io/part-of: grafana-loki
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
