version: '3.8'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.45
    container_name: jaeger
    restart: always
    command:
      - '--collector.otlp.enabled=true'
    ports:
      - "5775:5775/udp" # (deprecated) accept zipkin.thrift over compact Thrift protocol (used by legacy clients only)
      - "6831:6831/udp" # accept jaeger.thrift over Thrift-compact protocol (used by most SDKs)
      - "6832:6832/udp" # accept jaeger.thrift over Thrift-binary protocol (used by Node.js SDK)
      - "5778:5778" # serve configs (sampling, etc.)
      - "16686:16686" # serve frontend
      - "14268:14268" # accept jaeger.thrift directly from clients
      - "9411:9411" # Zipkin compatible endpoint (optional)
      - "14269:14269"
      - "4317:4317" # accept OpenTelemetry Protocol (OTLP) over gRPC, if enabled
      - "4318:4318" # accept OpenTelemetry Protocol (OTLP) over HTTP, if enabled
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
