http:
  address: 0.0.0.0:4195
  enabled: true
  debug_endpoints: true
logger:
  level: ALL
  format: logfmt
  add_timestamp: true
  static_fields:
    '@service': kafka-to-http
metrics:
  mapping: |
    meta service = "kafka-to-http"
    root = "benthos_metric_" + this
  statsd:
    address: ${STATSD_AGENT_HOST}
    flush_period: 100ms
    tag_format: datadog
tracer:
  jaeger:
    agent_address: ${JAEGER_AGENT_URL}
    collector_url: ${JAEGER_COLLECTOR_URL}
    sampler_type: const
    flush_interval: ""
