version: "3.8"
services:
  benthos_svc:
    image: jeffail/benthos:4.6.0
    restart: always
    command:
      - -c
      - /config/config.yaml
    ports:
      - "4196:4195"
    read_only: true
    volumes:
      - "./config.yaml:/config/config.yaml"
