server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /etc/promtail/positions/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: my_app_logs
    pipeline_stages:
      - docker: {}
    static_configs:
      - targets:
          - app_service:80 # Replace with your app service name and the port where your app logs to stdout
        labels:
          __path__: /var/log/*log
          agent: test-from-docker
