apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  labels:
    app.kubernetes.io/name: grafana-loki-config
    app.kubernetes.io/part-of: grafana-loki
data:
  config.yaml: |
    auth_enabled: true
    
    server:
      http_listen_address: 0.0.0.0
      grpc_listen_address: 0.0.0.0
      http_listen_port: 3100
      grpc_listen_port: 9095
      log_level: debug
      
    common:
      replication_factor: 1 # must be set number of minimum replication factor
      path_prefix: /data # Update this accordingly, data will be stored here.
      ring:
        kvstore:
          store: memberlist
      # my-svc.my-namespace.svc
      # https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/
      compactor_grpc_address: loki-compactor.loki.svc:9095
      
    limits_config:
      unordered_writes: true
      split_queries_by_interval: 1h
    
    memberlist:
      advertise_port: 7946
      # https://github.com/grafana/loki/blob/v2.8.3/docs/sources/fundamentals/architecture/rings/_index.md
      # Not all Loki components are connected by hash rings. These components need to be connected into a hash ring:
      # distributors, ingesters, query schedulers, compactors, rulers
      # These components can optionally be connected into a hash ring: index gateway
      # https://community.grafana.com/t/read-only-cluster-separated-from-main-cluster/77219/8
      join_members:
        # You can use a headless k8s service for all distributor, ingester and querier components.
        # <service-name>.<namespace>.svc
        - loki-compactor.loki.svc:7946 # :7946 is the default memberlist port.
        - loki-distributor.loki.svc:7946
        - loki-index-gateway.loki.svc:7946 
        - loki-ingester.loki.svc:7946 
        - loki-query-scheduler.loki.svc:7946 
        - loki-ruler.loki.svc:7946 
        
    schema_config:
      configs:
        - from: 2020-05-15
          store: tsdb
          object_store: s3
          schema: v12
          index:
            prefix: my-logs_ # directory prefix in the object store when saving the index
            period: 24h
            
    storage_config:
      tsdb_shipper:
        active_index_directory: /data/tsdb/index
        cache_location: /data/tsdb/index_cache
        shared_store: s3
        cache_ttl: 24h
        index_gateway_client:
          server_address: loki-index-gateway.loki.svc:9095
          log_gateway_requests: true
    
      aws:
        s3: http://minioadmin:minioadmin@minio.minio.svc:9000/loki-data
        s3forcepathstyle: true
        insecure: true
        bucketnames: loki-data
        access_key_id: "minio-access-key"
        secret_access_key: "minio-secret-key"
        
    ingester:
      lifecycler:
        join_after: 10s
        observe_period: 5s
        final_sleep: 0s
  
      wal:
        enabled: true
        dir: /data/ingester-wal
        checkpoint_duration: 5m
        flush_on_shutdown: true
        replay_memory_ceiling: 750MB
      chunk_idle_period: 1m
      chunk_retain_period: 30s
      chunk_encoding: gzip # none, gzip, lz4-64k, snappy, lz4-256k, lz4-1M, lz4, flate, zstd. Default: gzip
      chunk_target_size: 1572864 # Default = 1572864 bytes = 1.5 MB
      chunk_block_size: 262144
      flush_op_timeout: 10s
      max_chunk_age: 2h
  
    ruler:
      # https://github.com/grafana/loki/blob/v2.8.3/docs/sources/operations/recording-rules.md?plain=1#L82
      enable_sharding: true
      sharding_strategy: default
      sharding_algo: by-rule
      wal:
        dir: /data/ruler-wal
        truncate_frequency: 1h
        min_age: 5m
        max_age: 4h
      wal_cleaner:
        min_age: 5m # The minimum age of a WAL to consider for cleaning. Default = 12h
        period: 30s  # How often to run the WAL cleaner. 0 = disabled. Default = 0s
      storage:
        type: local
        local:
          directory: /data/ruler-dir
  
    ## ===== CONFIG FOR READ REPLICA ONLY (Query scheduler, querier and compactor)
    query_scheduler:
      max_outstanding_requests_per_tenant: 32768
  
    querier:
      max_concurrent: 16
      query_ingesters_within: 0
  
    ## ===== CONFIG FOR COMPACTOR ONLY
    compactor:
      working_directory: /data/compactor-dir
      shared_store: s3
      compaction_interval: 10m
  
    table_manager:
      retention_deletes_enabled: true
      retention_period: 8760h # 1year = 8760h
      
    ## ===== CONFIG FOR FRONT-END ONLY
    query_range:
      # make queries more cache-able by aligning them with their step intervals
      align_queries_with_step: true
      max_retries: 5
      parallelise_shardable_queries: true
      cache_results: true
      results_cache:
        cache:
          # We're going to use the in-process "FIFO" cache
          enable_fifocache: true
          fifocache:
            size: 1024
            validity: 24h
    
    frontend:
      log_queries_longer_than: 10s
      compress_responses: true
      max_outstanding_per_tenant: 2048
      scheduler_address: loki-query-scheduler.loki.svc:9095
      tail_proxy_url: http://loki-querier.loki.svc:3100 # URL of querier for tail proxy.
      downstream_url: http://loki-index-gateway.loki.svc:3100
    
    frontend_worker:
      # https://github.com/grafana/loki/issues/6369
      # frontend_address: loki-query-frontend.loki.svc:9095
      scheduler_address: loki-query-scheduler.loki.svc:9095
