apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-env
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: minio
data:
  env_file: |
    MINIO_ACCESS_KEY="minio-access-key"
    MINIO_SECRET_KEY="minio-secret-key"
    MINIO_ROOT_USER=minioadmin
    MINIO_ROOT_PASSWORD=minioadmin
