---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-dashboard-volume-claim
  labels:
    app.kubernetes.io/name: grafana-dashboard
    app.kubernetes.io/part-of: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
