apiVersion: v1
kind: Secret
metadata:
  name: otel-collector-secret-env
  labels:
    app: opentelemetry
    component: otel-agent-conf
  namespace: otel-demo-ns # This must be the same as spec.destination.namespace in argocd-app.yaml
data:
  # change this to real Datadog API Key in base64 encoded string
  # use command: echo "datadogKey" | base64
  DD_API_KEY: ""
