# Use root/password as user/password credentials
version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongodb
    platform: linux/arm64
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - './docker-data/mongodb:/data/db'

  mongo-express:
    image: mongo-express:0.54
    container_name: mongoexpress
    platform: linux/arm64
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
