# Source: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.79.0/exporter/datadogexporter/examples/k8s-chart/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector-deployment
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
    spec:
      serviceAccountName: otel-collector-account
      containers:
        - name: collector
          command:
            - "/otelcol-contrib"
            - "--config=/conf/otel-agent-config.yaml"
          image: otel/opentelemetry-collector-contrib:0.79.0
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 500Mi
          ports:
            - containerPort: 4318 # default port for OpenTelemetry HTTP receiver.
              hostPort: 4318
              name: otel-http
            - containerPort: 4317 # default port for OpenTelemetry gRPC receiver.
              hostPort: 4317
              name: otel-grpc
            - containerPort: 8888 # Default endpoint for querying metrics.
              hostPort: 8888
              name: otel-metric
          volumeMounts:
            - name: otel-agent-config-vol
              mountPath: /conf
            - name: varlogpods
              mountPath: /var/log/pods
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            # The k8s.pod.ip is used to associate pods with k8sattributes.
            # It is useful to have in the Collector pod because receiver metrics can also
            # benefit from the tags.
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "k8s.pod.ip=$(POD_IP)"
          envFrom:
            - secretRef:
                name: otel-collector-secret-env
      volumes:
        - name: otlpgen
          hostPath:
            path: /otlpgen
        - name: otel-agent-config-vol
          configMap:
            name: otel-collector-agent-conf
            items:
              - key: otel-agent-config
                path: otel-agent-config.yaml
        # Mount nodes log file location.
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers