apiVersion: v1
kind: Service
metadata:
  name: otel-collector-service
spec:
  selector:
    app: opentelemetry
    component: otel-collector
  ports:
    - name: http-port
      protocol: TCP
      port: 4318
      targetPort: otel-http
    - name: grpc-port
      protocol: TCP
      port: 4317
      targetPort: otel-grpc
    - name: metric-port
      protocol: TCP
      port: 8888
      targetPort: otel-metric